# Generated by Django 5.0.1 on 2025-08-20 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=100, help_text='Maximum patient capacity')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aamil', models.ForeignKey(limit_choices_to={'role': 'aamil'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_mozes', to=settings.AUTH_USER_MODEL)),
                ('moze_coordinator', models.ForeignKey(blank=True, limit_choices_to={'role': 'moze_coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_mozes', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, help_text='Team members assigned to this Moze', related_name='moze_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moze',
                'verbose_name_plural': 'Mozes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MozeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moze.moze')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='moze.mozecomment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MozeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_walk_ins', models.BooleanField(default=True)),
                ('appointment_duration', models.PositiveIntegerField(default=30, help_text='Default appointment duration in minutes')),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('working_days', models.JSONField(default=list, help_text='List of working days (0=Monday, 6=Sunday)')),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moze', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='moze.moze')),
            ],
            options={
                'verbose_name': 'Moze Settings',
                'verbose_name_plural': 'Moze Settings',
            },
        ),
        migrations.CreateModel(
            name='UmoorSehhatTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('sports', 'Sports'), ('nazafat', 'Nazafat'), ('environment', 'Environment')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umoor_team_memberships', to=settings.AUTH_USER_MODEL)),
                ('moze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umoor_teams', to='moze.moze')),
            ],
            options={
                'verbose_name': 'Umoor Sehhat Team Member',
                'verbose_name_plural': 'Umoor Sehhat Team Members',
                'ordering': ['category', 'member__first_name'],
                'unique_together': {('moze', 'member', 'category')},
            },
        ),
    ]
