# Generated by Django 5.0.1 on 2025-08-04 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moze', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmoorSehhatTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('sports', 'Sports'), ('nazafat', 'Nazafat'), ('environment', 'Environment')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umoor_team_memberships', to=settings.AUTH_USER_MODEL)),
                ('moze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umoor_teams', to='moze.moze')),
            ],
            options={
                'verbose_name': 'Umoor Sehhat Team Member',
                'verbose_name_plural': 'Umoor Sehhat Team Members',
                'ordering': ['category', 'member__first_name'],
                'unique_together': {('moze', 'member', 'category')},
            },
        ),
    ]
