# Generated by Django 5.0.1 on 2025-08-09 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('users', 'Users'), ('students', 'Students'), ('doctors', 'Doctors'), ('moze', 'Moze Centers'), ('surveys', 'Surveys'), ('evaluations', 'Evaluations'), ('patients', 'Patients'), ('medical_records', 'Medical Records')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_columns', models.JSONField(help_text='List of required column names')),
                ('optional_columns', models.JSONField(default=list, help_text='List of optional column names')),
                ('column_mappings', models.JSONField(default=dict, help_text='Mapping from column names to model fields')),
                ('validation_rules', models.JSONField(default=dict, help_text='Validation rules for each column')),
                ('sample_data', models.JSONField(default=list, help_text='Sample rows for the template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Upload Template',
                'verbose_name_plural': 'Upload Templates',
                'ordering': ['upload_type'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('users', 'Users'), ('students', 'Students'), ('doctors', 'Doctors'), ('moze', 'Moze Centers'), ('surveys', 'Surveys'), ('evaluations', 'Evaluations'), ('patients', 'Patients'), ('medical_records', 'Medical Records')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('processing_log', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Upload options and settings')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Upload Session',
                'verbose_name_plural': 'Bulk Upload Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(help_text='Original data from the row')),
                ('processed_data', models.JSONField(blank=True, help_text='Processed/cleaned data', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='bulk_upload.bulkuploadsession')),
            ],
            options={
                'verbose_name': 'Bulk Upload Record',
                'verbose_name_plural': 'Bulk Upload Records',
                'ordering': ['row_number'],
                'unique_together': {('session', 'row_number')},
            },
        ),
    ]
