# Generated by Django 5.0.1 on 2025-07-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='allow_uploads',
            field=models.BooleanField(default=True, help_text='Allow team members to upload photos'),
        ),
    ]
