# Generated by Django 5.0.1 on 2025-08-20 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('aamil', 'Aamils'), ('moze_coordinator', 'Moze Coordinators'), ('doctor', 'Doctors'), ('student', 'Students'), ('badri_mahal_admin', 'Badri Mahal Admins')], default='all', max_length=20)),
                ('questions', models.JSONField(default=list, help_text='List of questions in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('allow_multiple_responses', models.BooleanField(default=False)),
                ('show_results', models.BooleanField(default=False, help_text='Show results to respondents')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invitations', models.PositiveIntegerField(default=0)),
                ('total_responses', models.PositiveIntegerField(default=0)),
                ('total_complete_responses', models.PositiveIntegerField(default=0)),
                ('response_rate', models.FloatField(default=0.0, help_text='Response rate as percentage')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Completion rate as percentage')),
                ('avg_completion_time', models.FloatField(default=0.0, help_text='Average completion time in seconds')),
                ('detailed_analytics', models.JSONField(default=dict)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Survey Analytics',
                'verbose_name_plural': 'Survey Analytics',
            },
        ),
        migrations.CreateModel(
            name='SurveyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('max_reminders', models.PositiveIntegerField(default=3)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('has_responded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Reminder',
                'verbose_name_plural': 'Survey Reminders',
                'unique_together': {('survey', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Answers in JSON format matching question IDs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('completion_time', models.PositiveIntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'respondent')},
            },
        ),
    ]
