# Generated by Django 5.0.1 on 2025-07-21 06:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctordirectory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuaAraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_its_id', models.CharField(help_text='8-digit ITS ID of the patient', max_length=8, validators=[django.core.validators.RegexValidator(message='Patient ITS ID must be exactly 8 digits', regex='^\\d{8}$')])),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ailment', models.TextField(help_text='Description of the medical condition or concern')),
                ('symptoms', models.TextField(blank=True, help_text='Detailed symptoms', null=True)),
                ('urgency_level', models.CharField(choices=[('low', 'Low - Routine checkup'), ('medium', 'Medium - Some concern'), ('high', 'High - Urgent attention needed'), ('emergency', 'Emergency - Immediate attention required')], default='medium', max_length=20)),
                ('request_type', models.CharField(choices=[('consultation', 'Medical Consultation'), ('prescription', 'Prescription Request'), ('follow_up', 'Follow-up Appointment'), ('referral', 'Specialist Referral'), ('certificate', 'Medical Certificate'), ('second_opinion', 'Second Opinion'), ('health_advice', 'General Health Advice'), ('other', 'Other')], default='consultation', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned to Doctor'), ('scheduled', 'Appointment Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_response', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('priority_score', models.PositiveIntegerField(default=0, help_text='Internal priority score (0-10)')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_araz', to=settings.AUTH_USER_MODEL)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_araz', to='doctordirectory.doctor')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_araz', to=settings.AUTH_USER_MODEL)),
                ('preferred_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_araz', to='doctordirectory.doctor')),
            ],
            options={
                'verbose_name': 'Dua Araz',
                'verbose_name_plural': 'Dua Araz',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='ArazStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('araz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='araz.duaaraz')),
            ],
            options={
                'verbose_name': 'Araz Status History',
                'verbose_name_plural': 'Araz Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ArazNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('status_update', 'Status Update'), ('doctor_assigned', 'Doctor Assigned'), ('doctor_response', 'Doctor Response'), ('appointment_scheduled', 'Appointment Scheduled'), ('follow_up_reminder', 'Follow-up Reminder'), ('completion_notice', 'Completion Notice')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('araz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='araz.duaaraz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArazComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_type', models.CharField(choices=[('patient', 'Patient Communication'), ('doctor', 'Doctor Response'), ('admin', 'Administrative Note'), ('system', 'System Update')], default='admin', max_length=20)),
                ('is_visible_to_patient', models.BooleanField(default=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('araz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='araz.duaaraz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArazAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='araz_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('medical_report', 'Medical Report'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('image', 'Image/Photo'), ('document', 'Document'), ('other', 'Other')], default='document', max_length=20)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('araz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='araz.duaaraz')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
