# Generated by Django 5.0.1 on 2025-07-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('araz', '0001_initial'),
    ]

    operations = [
    ]
