# Generated by Django 5.0.1 on 2025-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctordirectory', '0001_initial'),
    ]

    operations = [
    ]
