# Generated by Django 5.0.1 on 2025-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordirectory', '0002_appointment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
