# Generated by Django 5.0.1 on 2025-08-16 11:34

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('doctordirectory', '0002_auto_20250812_1000'),
    ]

    operations = [
        # Add missing name field
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, default='Unknown Doctor'),
            preserve_default=False,
        ),
        # Add missing its_id field
        migrations.AddField(
            model_name='doctor',
            name='its_id',
            field=models.CharField(
                blank=True, 
                max_length=8, 
                null=True,
                validators=[django.core.validators.RegexValidator(
                    message='ITS ID must be exactly 8 digits', 
                    regex='^\\d{8}$'
                )]
            ),
        ),
    ]
